# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Gia Lang
email: gia.arah@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Creative and Professional Portfolio of Gia Lang.
github_username: GiaArah
minimal_mistakes_skin: dark # default
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
# permalink: /:categories/:title/
# paginate: 1 # amount of posts to show
# paginate_path: /page:num/
# timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Add folders to include in builds
include:
  - _pages
  - game-design

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Gia Lang"
  avatar : "/assets/images/lang_bio_photo.jpg"
  bio    : "sound designer, game designer, programmer." 
  links:
    - label: "Email"
      icon: "fa-solid fa-envelope"
      url: "mailto:gia.arah@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/GiaArah"
    - label: "Itch"
      icon: "fa-brands fa-itch-io"
      url: "https://giaarah.itch.io/"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/gia-lang/"

footer:
  show_feed: false 
  links:
    - label: "Email"
      icon: "fa-solid fa-envelope"
      url: "mailto:gia.arah@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/GiaArah"
    - label: "Itch"
      icon: "fa-brands fa-itch-io"
      url: "https://giaarah.itch.io/"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/gia-lang/"

defaults:
  # # _posts
  # - scope:
  #     path: ""
  #     type: posts
  #   values:
  #     layout: single
  #     author_profile: true
  #     read_time: true
  #     comments: true
  #     share: true
  #     related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: "_game-design"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

favicon: "/assets/images/control_knobs.png"
